export const ESTADO_SECTIONS = {
    USUARIO: 'USUARIO',
    MANTENIMIENTO: 'MANTENIMIENTO',
    VIAJE: 'VIAJE',
    FACTURA: 'FACTURA',
    FACTURA_PAGO: 'FACTURA_PAGO',
} as const;

export const TIPO_MAESTRO_SECTIONS = {
    FLOTA: 'VEHICULO',
    PESO: 'PESO',
    MEDIDA: 'MEDIDA',
    DOCUMENTO_FLOTA: 'DOCUMENTO_FLOTA',
    SEXO: 'SEXO',
    LICENCIA: 'LICENCIA',
    PAGO: 'PAGO',
    PRODUCTO: 'PRODUCTO',
    SERVICIO: 'MANTENIMIENTO',
    GUIA: 'GUIA',
    INCIDENTE: 'INCIDENTE',
    ESTADO_FACTURA: 'ESTADO_FACTURA',
    MEDIO_PAGO: 'MEDIO_PAGO',
    PUNTO_RUTA: 'PUNTO_RUTA',
    COMBUSTIBLE: 'COMBUSTIBLE',
} as const;

export const MONEDA_CODES = {
    PEN: 'PEN',
    USD: 'USD',
    EUR: 'EUR',
} as const;

export const ESTADO_SECCIONES = ESTADO_SECTIONS;
export const SECCION_MAESTRO = TIPO_MAESTRO_SECTIONS;
