export const PERMISSIONS = {
    DASHBOARD: {
        VER: 'DASHBOARD_VER',
    },
    CLIENTES: {
        VER: 'CLIENTES_VER',
        GESTIONAR: 'CLIENTES_GESTIONAR',
    },
    COTIZACIONES: {
        VER: 'COTIZACIONES_VER',
        GESTIONAR: 'COTIZACIONES_GESTIONAR',
    },
    FACTURAS: {
        VER: 'FACTURAS_VER',
        GESTIONAR: 'FACTURAS_GESTIONAR',
    },
    VIAJES: {
        VER: 'VIAJES_VER',
        GESTIONAR: 'VIAJES_GESTIONAR',
        REABRIR: 'VIAJES_REABRIR',
        CERRAR: 'VIAJES_CERRAR',
    },
    FLOTA: {
        VER: 'FLOTA_VER',
        GESTIONAR: 'FLOTA_GESTIONAR',
    },
    COLABORADORES: {
        VER: 'COLABORADORES_VER',
        GESTIONAR: 'COLABORADORES_GESTIONAR',
        GESTIONAR_SOLICITUDES_DOCUMENTOS: 'COLABORADORES_DOCUMENTOS_SOLICITUDES_GESTIONAR',
        APROBAR_LICENCIAS: 'COLABORADORES_LICENCIAS_APROBAR',
    },
    MANTENIMIENTOS: {
        VER: 'MANTENIMIENTOS_VER',
        GESTIONAR: 'MANTENIMIENTOS_GESTIONAR',
        REABRIR:'MANTENIMIENTOS_REABRIR',
    },
    SISTEMA: {
        USUARIOS: {
            VER: 'USUARIOS_VER',
            GESTIONAR: 'USUARIOS_GESTIONAR',
        },
        ROLES: {
            VER: 'ROLES_VER',
            GESTIONAR: 'ROLES_GESTIONAR',
        },
        MAESTROS: {
            VER: 'MAESTROS_VER',
            GESTIONAR: 'MAESTROS_GESTIONAR',
        }
    },
    CATALOGOS: {
        TIPO_PRODUCTO: { VER: 'TIPO_PRODUCTO_VER', GESTIONAR: 'TIPO_PRODUCTO_GESTIONAR' },
        MERCADERIA: { VER: 'MERCADERIA_VER', GESTIONAR: 'MERCADERIA_GESTIONAR' },
        GASTO: { VER: 'GASTO_VER', GESTIONAR: 'GASTO_GESTIONAR' },
    }
} as const;
