export const PERMISSIONS = {
    DASHBOARD: {
        VER: 'DASHBOARD_VER',
    },
    EMPLOYEE: {
        VIAJES: {
            VER: 'PORTAL_EMPLEADO_VIAJES_VER',
            GESTIONAR: 'PORTAL_EMPLEADO_VIAJES_GESTIONAR',
        },
        PAGOS: {
            VER: 'PORTAL_EMPLEADO_PAGOS_VER',
            CONFIRMAR: 'PORTAL_EMPLEADO_PAGOS_CONFIRMAR',
        },
        LICENCIAS: {
            VER: 'PORTAL_EMPLEADO_LICENCIAS_VER',
            SOLICITAR: 'PORTAL_EMPLEADO_LICENCIAS_SOLICITAR',
        },
        DOCUMENTOS: {
            VER: 'PORTAL_EMPLEADO_DOCUMENTOS_VER',
            SOLICITAR_ACTUALIZACION: 'PORTAL_EMPLEADO_DOCUMENTOS_SOLICITAR_ACTUALIZACION',
        },
        AVATAR: {
            ACTUALIZAR: 'USUARIO_AVATAR_ACTUALIZAR',
        },
    },
    CLIENTES: {
        VER: 'CLIENTES_VER',
        GESTIONAR: 'CLIENTES_GESTIONAR',
    },
    COTIZACIONES: {
        VER: 'COTIZACIONES_VER',
        GESTIONAR: 'COTIZACIONES_GESTIONAR',
    },
    FACTURAS: {
        VER: 'FACTURAS_VER',
        GESTIONAR: 'FACTURAS_GESTIONAR',
    },
    VIAJES: {
        VER: 'VIAJES_VER',
        GESTIONAR: 'VIAJES_GESTIONAR',
        REABRIR: 'VIAJES_REABRIR',
    },
    FLOTA: {
        VER: 'FLOTA_VER',
        GESTIONAR: 'FLOTA_GESTIONAR',
    },
    COLABORADORES: {
        VER: 'COLABORADORES_VER',
        GESTIONAR: 'COLABORADORES_GESTIONAR',
    },
    MANTENIMIENTOS: {
        VER: 'MANTENIMIENTOS_VER',
        GESTIONAR: 'MANTENIMIENTOS_GESTIONAR',
        REABRIR:'MANTENIMIENTOS_REABRIR',
    },
    SISTEMA: {
        USUARIOS: {
            VER: 'USUARIOS_VER',
            GESTIONAR: 'USUARIOS_GESTIONAR',
        },
        ROLES: {
            VER: 'ROLES_VER',
            GESTIONAR: 'ROLES_GESTIONAR',
        },
        MAESTROS: {
            VER: 'MAESTROS_VER',
            GESTIONAR: 'MAESTROS_GESTIONAR',
        }
    },
    CATALOGOS: {
        TIPO_PRODUCTO: { VER: 'TIPO_PRODUCTO_VER', GESTIONAR: 'TIPO_PRODUCTO_GESTIONAR' },
        MERCADERIA: { VER: 'MERCADERIA_VER', GESTIONAR: 'MERCADERIA_GESTIONAR' },
        GASTO: { VER: 'GASTO_VER', GESTIONAR: 'GASTO_GESTIONAR' },
    }
} as const;
